export const LOADING_PROMOTIONS = "LOADING_PROMOTIONS";
export const GET_PROMOTIONS = "GET_PROMOTIONS";
export const GET_PROMOTIONS_FAIL = "GET_PROMOTIONS_FAIL";

export const SELECT_PROMOTION = "SELECT_PROMOTION";
export const CLEAR_PROMOTIONS = "CLEAR_PROMOTIONS";

export const GET_PHONE_NUMBER = "GET_PHONE_NUMBER";
