export const SET_LOADING = "SET_LOADING";
export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const LOADING_DELETE_CONTACT = "LOADING_DELETE_CONTACT";
export const CONTACT_DELETE = "CONTACT_DELETE";
export const CONTACT_DELETE_FAIL = "CONTACT_DELETE_FAIL";

export const SELECT_CONTACT = "SELECT_CONTACT";

export const LOADING_UPDATE_CONTACT = "LOADING_UPDATE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_CONTACT_FAIL = "UPDATE_CONTACT_FAIL";

export const LOADING_CREATE_CONTACT = "LOADING_CREATE_CONTACT";
export const CREATE_CONTACT = "CREATE_CONTACT";
export const CREATE_CONTACT_FAIL = "CREATE_CONTACT_FAIL";

export const CLEAR_SELECTED_CONTACT = "CLEAR_SELECTED_CONTACT";

export const SET_FILTERS = "SET_FILTERS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
