export const SELECT_OWN_PHONE = "SELECT_OWN_PHONE";
export const SELECT_CONFIRM_CHARGE_PHONE = "SELECT_CONFIRM_CHARGE_PHONE";
export const SET_NEW_CONTACT_NAME = "SET_NEW_CONTACT_NAME";

export const CHECK_ADD_CONTACT = "CHECK_ADD_CONTACT";

export const LOADING_METHODS_TYPE = "LOADING_METHODS_TYPE";
export const METHODS_TYPE = "METHODS_TYPE";
export const METHODS_TYPE_FAIL = "METHODS_TYPE_FAIL";

export const PROCESSING_PAYMENT = "PROCESSING_PAYMENT";
export const PAYMENT_COMPLETED = "PAYMENT_COMPLETED";
export const PAYMENT_FAILED = "PAYMENT_FAILED";

export const LOADING_RATES = "LOADING_RATES";
export const METHODS_RATES = "METHODS_RATES";
export const METHODS_RATES_FAIL = "METHODS_RATES_FAIL";

export const LOADING_CARD_SETTINGS = "LOADING_CARD_SETTINGS";
export const METHODS_CARD = "METHODS_CARD";
export const METHODS_CARD_FAIL = "METHODS_CARD_FAIL";

export const LOADING_PAY_CARD = "LOADING_PAY_CARD";
export const METHODS_PAY_CC = "METHODS_PAY_CC";
export const METHODS_PAY_CC_FAIL = "METHODS_PAY_CC_FAIL";

export const LOADING_PAY_CARD_ORDER = "LOADING_PAY_CARD_ORDER";
export const METHODS_PAY_CC_ORDER = "METHODS_PAY_CC_ORDER";
export const METHODS_PAY_CC_ORDER_FAIL = "METHODS_PAY_CC_ORDER_FAIL";

export const CARD_SETTINGS_UPLOAD = "CARD_SETTINGS_UPLOAD";

export const PAYMENT_RESET = "PAYMENT_RESET";
