export const SELECT_OWN_PHONE = "SELECT_OWN_PHONE";
export const SELECT_CONFIRM_CHARGE_PHONE = "SELECT_CONFIRM_CHARGE_PHONE";

export const CHECK_ADD_CONTACT = "CHECK_ADD_CONTACT";

export const LOADING_METHODS_TYPE = "LOADING_METHODS_TYPE";
export const METHODS_TYPE = "METHODS_TYPE";
export const METHODS_TYPE_FAIL = "METHODS_TYPE_FAIL";

export const PROCESSING_PAYMENT = "PROCESSING_PAYMENT";
export const PAYMENT_COMPLETED = "PAYMENT_COMPLETED";
export const PAYMENT_FAILED = "PAYMENT_FAILED";

export const LOADING_RATES = "LOADING_RATES";
export const METHODS_RATES = "METHODS_RATES";
export const METHODS_RATES_FAIL = "METHODS_RATES_FAIL";

export const PAYMENT_RESET = "PAYMENT_RESET";
