export const LOADING = "LOADING";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";

export const LOADING_REGISTER = "LOADING_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOADING_COUNTRIES = "LOADING_COUNTRIES";
export const COUNTRIES_SUCCESS = "COUNTRIES_SUCCESS";
export const COUNTRIES_FAIL = "COUNTRIES_FAIL";

export const LOADING_CONFIRM = "LOADING_CONFIRM";
export const CONFIRM_SUCCESS = "CONFIRM_SUCCESS";
export const CONFIRM_FAIL = "CONFIRM_FAIL";

export const UPDT_USER_DATA = "UPDT_USER_DATA";

export const LOADING_SEND_CODE = "LOADING_SEND_CODE";
export const SEND_CODE_SUCCESS = "SEND_CODE_SUCCESS";
export const SEND_CODE_FAIL = "SEND_CODE_FAIL";

export const LOADING_RECOVER_PW = "LOADING_RECOVER_PW";
export const RECOVER_PW_SUCCESS = "RECOVER_PW_SUCCESS";
export const RECOVER_PW_FAIL = "RECOVER_PW_FAIL";
